version: '3.5'
services:
  infertrade-frontend-A:
    image: eu.gcr.io/analog-antler-216014/infertrade-frontend:${TAG:-deploy-A}
    ports:
      - "8080:80"
    build:
      context: ..
      args:
      - REACT_APP_API_URL
      - PORT
    restart: always
