version: '3.5'
services:
  infertrade-frontend-B:
    image: eu.gcr.io/analog-antler-216014/infertrade-frontend:${TAG:-deploy-B}
    ports:
      - "8081:80"
    build:
      context: ..
      args:
      - REACT_APP_API_URL
      - PORT
    restart: always
